### ISSUE TITLE
Getting a 404 :)

### ISSUE THREAD

**Issue by GarnetSunset** [AbdelrhmanNile/UnderTaker141#1]
**Describe the bug**
Getting a 404 that crashes the app!

**To Reproduce**
Open the app!

**Desktop (please complete the following information):**
 - OS: Steam Deck

**Additional context**
```
INFO   ] [Loader      ] using a thread pool of 2 workers
[DEBUG  ] [Parsed user URL] ParseResult(scheme='', netloc='localhost', path='', params='', query='', fragment='')
[DEBUG  ] Detecting scheme for URL...
[DEBUG  ] [Starting new HTTP connection (1)] localhost:8080
[DEBUG  ] [http          ]//localhost:8080 "HEAD / HTTP/1.1" 200 0
[DEBUG  ] Using HTTP scheme
[DEBUG  ] [Base URL    ] http://localhost:8080/
[DEBUG  ] [Starting new HTTP connection (1)] localhost:8080
[DEBUG  ] [http          ]//localhost:8080 "POST /api/v2/torrents/info HTTP/1.1" 404 0
 Traceback (most recent call last):
   File "/tmp/.mount_UnderTtiZQaA/opt/src/app.py", line 12, in <module>
     UnderTaker141().run()
   File "/tmp/.mount_UnderTtiZQaA/opt/python3.11/lib/python3.11/site-packages/kivy/app.py", line 955, in run
     self._run_prepare()
   File "/tmp/.mount_UnderTtiZQaA/opt/python3.11/lib/python3.11/site-packages/kivy/app.py", line 925, in _run_prepare
     root = self.build()
            ^^^^^^^^^^^^
   File "/tmp/.mount_UnderTtiZQaA/opt/src/app.py", line 9, in build
     return MainScreen()
            ^^^^^^^^^^^^
   File "/tmp/.mount_UnderTtiZQaA/opt/src/widgets/core/core.py", line 41, in __init__
     self.load_screens()
   File "/tmp/.mount_UnderTtiZQaA/opt/src/widgets/core/core.py", line 101, in load_screens
     screen = screen_class(name=plugin.name) # create instance of a screen class
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/.mount_UnderTtiZQaA/opt/src/screens/library.py", line 41, in __init__
     self.load_library()
   File "/tmp/.mount_UnderTtiZQaA/opt/src/screens/library.py", line 46, in load_library
     torrs = qbt.get_torrents()
             ^^^^^^^^^^^^^^^^^^
   File "/tmp/.mount_UnderTtiZQaA/opt/src/utils/qbt.py", line 25, in get_torrents
     return self.qbt_client.torrents_info(tag="jc141")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/.mount_UnderTtiZQaA/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 117, in wrapper
     return func(client, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/.mount_UnderTtiZQaA/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 91, in wrapper
     return func(client, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/.mount_UnderTtiZQaA/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 1801, in torrents_info
     return self._post(
            ^^^^^^^^^^^
   File "/tmp/.mount_UnderTtiZQaA/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/request.py", line 390, in _post
     return self._request_manager(
            ^^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/.mount_UnderTtiZQaA/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/request.py", line 465, in _request_manager
     return self._request(
            ^^^^^^^^^^^^^^
   File "/tmp/.mount_UnderTtiZQaA/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/request.py", line 542, in _request
     self._handle_error_responses(data, params, response)
   File "/tmp/.mount_UnderTtiZQaA/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/request.py", line 773, in _handle_error_responses
     raise NotFound404Error(error_message)
 qbittorrentapi.exceptions.NotFound404Error
```

**Comment by AbdelrhmanNile** [comment]
make sure qbittorrent installed and its webui is running on localhost:8080

**Comment by GarnetSunset** [comment]
Gotchu!
