### ISSUE TITLE
launcher failed to open on Linux Mint

### ISSUE THREAD

**Issue by catalin560** [AbdelrhmanNile/UnderTaker141#10]
```
rexton@LinuxMint:~/Downloads$ ./UnderTaker141.AppImage 
[INFO   ] [Logger      ] Record log in /home/rexton/.kivy/logs/kivy_23-10-14_2.txt
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "/tmp/.mount_UnderTEUAlqB/opt/python3.11/lib/python3.11/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.11.4 (main, Aug  6 2023, 22:32:50) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
[INFO   ] [Python      ] Interpreter at "/home/rexton/Downloads/UnderTaker141.AppImage"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-09-29 (installed at "/tmp/.mount_UnderTEUAlqB/opt/python3.11/lib/python3.11/site-packages/kivymd/__init__.py")
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 23.2.0-devel'>
[INFO   ] [GL          ] OpenGL vendor <b'AMD'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon RX 6600 XT (navi23, LLVM 16.0.6, DRM 3.54, 5.15.0-86-generic)'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "/tmp/.mount_UnderTEUAlqB/opt/src/app.py", line 19, in <module>
     UnderTaker141().run()
   File "/tmp/.mount_UnderTEUAlqB/opt/python3.11/lib/python3.11/site-packages/kivy/app.py", line 955, in run
     self._run_prepare()
   File "/tmp/.mount_UnderTEUAlqB/opt/python3.11/lib/python3.11/site-packages/kivy/app.py", line 925, in _run_prepare
     root = self.build()
            ^^^^^^^^^^^^
   File "/tmp/.mount_UnderTEUAlqB/opt/src/app.py", line 9, in build
     check_config()
   File "/tmp/.mount_UnderTEUAlqB/opt/src/utils/settings.py", line 28, in check_config
     user_name = os.getlogin()
                 ^^^^^^^^^^^^^
 OSError: [Errno 6] No such device or address
```

**Comment by AbdelrhmanNile** [comment]
@catalin560 
i dont really know whats causing this
check this? https://bugs.python.org/issue40821
try executing the appimage from a terminal and let me know if it worked

**Comment by evild4ve** [comment]
On Xubuntu 22.04 I have the same error, ending "line 28, in check_config
     user_name = os.getlogin()
                 ^^^^^^^^^^^^^
 OSError: [Errno 6] No such device or address"

That python.org page concludes with "You have to get the user information by other means. Our documentation for os.getlogin() recommends getpass.getuser()."

**Comment by AbdelrhmanNile** [comment]
@evild4ve 
jc141 repacks doesnt have support for ubuntu distros anyway

**Comment by catalin560** [comment]
> @evild4ve jc141 repacks dont have support for ubuntu distros anyway

uhm, yeah they do https://gitlab.com/jc141x/setup#debian-based

**Comment by AbdelrhmanNile** [comment]
@catalin560 
no they dont :)
`Including: Debian Sid, Sparky Rolling and Siduction`
they actually advice against using ubuntu and its derivatives

**Comment by AbdelrhmanNile** [comment]
debian is not ubuntu

**Comment by catalin560** [comment]
> debian is not ubuntu

no one said that, Ubuntu is Debian based... I tried their setup scripts on Linux Mint and had no issues

**Comment by DDanii** [comment]
This should be fixed in the new version please retest

**Comment by DDanii** [comment]
I think we can close this.
