### ISSUE TITLE
Fail on startup

### ISSUE THREAD

**Issue by ajsnyde** [AbdelrhmanNile/UnderTaker141#13]
Tried connecting to previously existing qbittorrent instance, on Ubuntu 24.04 LTS.

```
./UnderTaker141.AppImage 
[INFO   ] [Logger      ] Record log in /home/dread/.kivy/logs/kivy_24-06-11_5.txt
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "/tmp/.mount_UnderTskp2Lv/opt/python3.11/lib/python3.11/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.11.4 (main, Aug  6 2023, 22:32:50) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
[INFO   ] [Python      ] Interpreter at "/home/dread/Downloads/UnderTaker141.AppImage"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-10-19 (installed at "/tmp/.mount_UnderTskp2Lv/opt/python3.11/lib/python3.11/site-packages/kivymd/__init__.py")
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 535.171.04'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce RTX 2080/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
sh: 1: qbittorrent: not found
[DEBUG  ] Re-initializing context...
[DEBUG  ] Re-initializing context...
[DEBUG  ] [Parsed user URL] ParseResult(scheme='', netloc='localhost', path='', params='', query='', fragment='')
[DEBUG  ] Detecting scheme for URL...
[DEBUG  ] [Starting new HTTP connection (1)] localhost:8080
[DEBUG  ] [http          ]//localhost:8080 "HEAD / HTTP/1.1" 200 0
[DEBUG  ] Using HTTP scheme
[DEBUG  ] [Base URL    ] http://localhost:8080/
[DEBUG  ] [Starting new HTTP connection (1)] localhost:8080
[DEBUG  ] [http          ]//localhost:8080 "POST /api/v2/auth/login HTTP/1.1" 200 3
[DEBUG  ] Login successful
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [Loader      ] using a thread pool of 2 workers
[DEBUG  ] Re-initializing context...
[DEBUG  ] [Parsed user URL] ParseResult(scheme='', netloc='localhost', path='', params='', query='', fragment='')
[DEBUG  ] Detecting scheme for URL...
[DEBUG  ] [Starting new HTTP connection (1)] localhost:8080
[DEBUG  ] [http          ]//localhost:8080 "HEAD / HTTP/1.1" 200 0
[DEBUG  ] Using HTTP scheme
[DEBUG  ] [Base URL    ] http://localhost:8080/
[DEBUG  ] [Starting new HTTP connection (1)] localhost:8080
[DEBUG  ] [http          ]//localhost:8080 "POST /api/v2/auth/login HTTP/1.1" 200 3
[DEBUG  ] Login successful
[DEBUG  ] Re-initializing context...
[DEBUG  ] [Parsed user URL] ParseResult(scheme='', netloc='localhost', path='', params='', query='', fragment='')
[DEBUG  ] Detecting scheme for URL...
[DEBUG  ] [Starting new HTTP connection (1)] localhost:8080
[DEBUG  ] [http          ]//localhost:8080 "HEAD / HTTP/1.1" 200 0
[DEBUG  ] Using HTTP scheme
[DEBUG  ] [Base URL    ] http://localhost:8080/
[DEBUG  ] [Starting new HTTP connection (1)] localhost:8080
[DEBUG  ] [http          ]//localhost:8080 "POST /api/v2/auth/login HTTP/1.1" 200 3
[DEBUG  ] Login successful
[DEBUG  ] [http          ]//localhost:8080 "POST /api/v2/torrents/info HTTP/1.1" 200 161029
 Traceback (most recent call last):
   File "/tmp/.mount_UnderTskp2Lv/opt/src/app.py", line 19, in <module>
     UnderTaker141().run()
   File "/tmp/.mount_UnderTskp2Lv/opt/python3.11/lib/python3.11/site-packages/kivy/app.py", line 955, in run
     self._run_prepare()
   File "/tmp/.mount_UnderTskp2Lv/opt/python3.11/lib/python3.11/site-packages/kivy/app.py", line 925, in _run_prepare
     root = self.build()
            ^^^^^^^^^^^^
   File "/tmp/.mount_UnderTskp2Lv/opt/src/app.py", line 16, in build
     return MainScreen(__version__)
            ^^^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/.mount_UnderTskp2Lv/opt/src/widgets/core/core.py", line 56, in __init__
     self.load_screens()
   File "/tmp/.mount_UnderTskp2Lv/opt/src/widgets/core/core.py", line 126, in load_screens
     screen = screen_class(name=plugin.name, qbt_client=self.qbt_client) # create instance of a screen class
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/.mount_UnderTskp2Lv/opt/src/screens/library.py", line 37, in __init__
     self.load_library()
   File "/tmp/.mount_UnderTskp2Lv/opt/src/screens/library.py", line 48, in load_library
     self.layout.add_widget(GameLibraryCard(game_torrent=game, qbt_client=self.qbt_client))            
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/.mount_UnderTskp2Lv/opt/src/widgets/game/game.py", line 86, in __init__
     self.game_obj = self.query_game(self.game_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/.mount_UnderTskp2Lv/opt/src/widgets/game/game.py", line 185, in query_game
     return db.get_library_game(partial_name)[0]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
 IndexError: list index out of range
```

**Comment by DDanii** [comment]
Can you retest it with newest version?
