### ISSUE TITLE
Appimage opens for a second and closes immediately on SteamOS

### ISSUE THREAD

**Issue by Mandydeth** [AbdelrhmanNile/UnderTaker141#4]
When trying to launch the appimage, it closes after about 2 seconds. I've copied my log from console.

    [INFO   ] [Logger      ] Record log in /home/deck/.kivy/logs/kivy_23-09-07_6.txt
    [INFO   ] [Kivy        ] v2.2.1
    [INFO   ] [Kivy        ] Installed at "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/kivy/__init__.py"
    [INFO   ] [Python      ] v3.11.4 (main, Aug  6 2023, 22:32:50) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
    [INFO   ] [Python      ] Interpreter at "/home/deck/Downloads/UnderTaker141.AppImage"
    [INFO   ] [Logger      ] Purge log fired. Processing...
    [INFO   ] [Logger      ] Purge finished!
    [INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-09-06 (installed at "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/kivymd/__init__.py")
    [INFO   ] [Factory     ] 190 symbols loaded
    [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
    [INFO   ] [Text        ] Provider: sdl2
    [INFO   ] [Window      ] Provider: sdl2
    [INFO   ] [GL          ] Using the "OpenGL" graphics system
    [INFO   ] [GL          ] Backend used <sdl2>
    [INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 22.2.0 (git-17e5312102)'>
    [INFO   ] [GL          ] OpenGL vendor <b'AMD'>
    [INFO   ] [GL          ] OpenGL renderer <b'AMD Custom GPU 0405 (vangogh, LLVM 14.0.6, DRM 3.45, 5.13.0-valve37-1-neptune)'>
    [INFO   ] [GL          ] OpenGL parsed version: 4, 6
    [INFO   ] [GL          ] Shading version <b'4.60'>
    [INFO   ] [GL          ] Texture max size <16384>
    [INFO   ] [GL          ] Texture max units <32>
    [INFO   ] [Window      ] auto add sdl2 input provider
    [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
    sh: line 1: qbittorrent: command not found
    [DEBUG  ] Re-initializing context...
    sh: line 1: qbittorrent: command not found
    [DEBUG  ] Re-initializing context...
    [INFO   ] [Clipboard   ] Provider: sdl2(['clipboard_xclip', 'clipboard_xsel', 'clipboard_dbusklipper', 'clipboard_gtk3'] ignored)
    [CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
    xclip - FileNotFoundError: [Errno 2] No such file or directory: 'xclip'
      File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
        mod = importlib.__import__(name='{2}.{0}.{1}'.format(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1283, in __import__
      File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
        p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/subprocess.py", line 1026, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    
    xsel - FileNotFoundError: [Errno 2] No such file or directory: 'xsel'
      File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
        mod = importlib.__import__(name='{2}.{0}.{1}'.format(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1283, in __import__
      File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/kivy/core/clipboard/clipboard_xsel.py", line 16, in <module>
        p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/subprocess.py", line 1026, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    
    [INFO   ] [Loader      ] using a thread pool of 2 workers
    [DEBUG  ] [Parsed user URL] ParseResult(scheme='', netloc='localhost', path='', params='', query='', fragment='')
    [DEBUG  ] Detecting scheme for URL...
    [DEBUG  ] [Starting new HTTP connection (1)] localhost:8080
    [DEBUG  ] [http          ]//localhost:8080 "HEAD / HTTP/1.1" 200 0
    [DEBUG  ] Using HTTP scheme
    [DEBUG  ] [Base URL    ] http://localhost:8080/
    [DEBUG  ] [Starting new HTTP connection (1)] localhost:8080
    [DEBUG  ] [http          ]//localhost:8080 "POST /api/v2/torrents/info HTTP/1.1" 404 0
     Traceback (most recent call last):
       File "/tmp/.mount_UnderT7AvCtk/opt/src/app.py", line 19, in <module>
         UnderTaker141().run()
       File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/kivy/app.py", line 955, in run
         self._run_prepare()
       File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/kivy/app.py", line 925, in _run_prepare
         root = self.build()
                ^^^^^^^^^^^^
       File "/tmp/.mount_UnderT7AvCtk/opt/src/app.py", line 16, in build
         return MainScreen()
                ^^^^^^^^^^^^
       File "/tmp/.mount_UnderT7AvCtk/opt/src/widgets/core/core.py", line 42, in __init__
         self.load_screens()
       File "/tmp/.mount_UnderT7AvCtk/opt/src/widgets/core/core.py", line 102, in load_screens
         screen = screen_class(name=plugin.name) # create instance of a screen class
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       File "/tmp/.mount_UnderT7AvCtk/opt/src/screens/library.py", line 39, in __init__
         self.load_library()
       File "/tmp/.mount_UnderT7AvCtk/opt/src/screens/library.py", line 44, in load_library
         torrs = qbt.get_torrents()
                 ^^^^^^^^^^^^^^^^^^
       File "/tmp/.mount_UnderT7AvCtk/opt/src/utils/qbt.py", line 25, in get_torrents
         return self.qbt_client.torrents_info(tag="jc141")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 117, in wrapper
         return func(client, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 91, in wrapper
         return func(client, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 1801, in torrents_info
         return self._post(
                ^^^^^^^^^^^
       File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/request.py", line 390, in _post
         return self._request_manager(
                ^^^^^^^^^^^^^^^^^^^^^^
       File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/request.py", line 465, in _request_manager
         return self._request(
                ^^^^^^^^^^^^^^
       File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/request.py", line 542, in _request
         self._handle_error_responses(data, params, response)
       File "/tmp/.mount_UnderT7AvCtk/opt/python3.11/lib/python3.11/site-packages/qbittorrentapi/request.py", line 773, in _handle_error_responses
         raise NotFound404Error(error_message)
         qbittorrentapi.exceptions.NotFound404Error

**Comment by AbdelrhmanNile** [comment]
@Mandydeth install qbittorrent and enable its webui
on localhost
port 8080

**Comment by AbdelrhmanNile** [comment]
default user and password for webui
admin
adminadmin

**Comment by AbdelrhmanNile** [comment]
@Mandydeth please let me know if it worked on your steam deck and was able to successfully download and launch a game
also do not forget to install all required dependencies for jc141 repacks
more about it [here](https://github.com/jc141x/jc141-bash/blob/master/setup/en/readme.md)

**Comment by AbdelrhmanNile** [comment]
@Mandydeth oh okay, ill patch it up and let you know!

**Comment by AbdelrhmanNile** [comment]
let me know if it worked

**Comment by Mandydeth** [comment]
The downloading functionality is fine. Looks like it's a headache to get the actual games functioning on deck, I'll have to mess with it later.

https://github.com/jc141x/jc141-bash/blob/master/setup/en/steamdeck/arch.md
