### ISSUE TITLE
Error running appimage

### ISSUE THREAD

**Issue by Kyouma960** [AbdelrhmanNile/UnderTaker141#6]
**Describe the bug**
``` Traceback (most recent call last):
   File "/tmp/.mount_UnderT8Io2Py/opt/src/app.py", line 19, in <module>
     UnderTaker141().run()
   File "/tmp/.mount_UnderT8Io2Py/opt/python3.11/lib/python3.11/site-packages/kivy/app.py", line 955, in run
     self._run_prepare()
   File "/tmp/.mount_UnderT8Io2Py/opt/python3.11/lib/python3.11/site-packages/kivy/app.py", line 925, in _run_prepare
     root = self.build()
            ^^^^^^^^^^^^
   File "/tmp/.mount_UnderT8Io2Py/opt/src/app.py", line 16, in build
     return MainScreen(__version__)
            ^^^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/.mount_UnderT8Io2Py/opt/src/widgets/core/core.py", line 27, in __init__
     self.qbt_client = JCQbt(settings["qbittorrent_api"]["host"],
                             ~~~~~~~~^^^^^^^^^^^^^^^^^^^
 TypeError: 'NoneType' object is not subscriptable
```
**Desktop:**
 -  Arch Hyprland

**Additional context**
qbittorrent webui is enabled, and all the dependencies mentioned by johncena is installed.

**Comment by Kyouma960** [comment]
Undertaker v2.0.0

**Comment by AbdelrhmanNile** [comment]
oh, found the bug in the code and fixed it
delete `~/.config/undertaker141` if you have it and download v2.0.1 from [here](https://github.com/AbdelrhmanNile/UnderTaker141/releases/tag/latest)
